USE bco_relacional;

SELECT *
FROM USUARIOS;

SELECT *
FROM FILMES;

SELECT *
FROM AVALIACOES;

-- Consulta 01 — Usuários e seus filmes avaliados 
SELECT U.NOME, F.TITULO, A.NOTA
FROM USUARIOS U 
INNER JOIN AVALIACOES A ON A.USUARIO_ID = U.USUARIO_ID
INNER JOIN FILMES F ON F.FILME_ID = A.FILME_ID
ORDER BY U.NOME;

-- Consulta 02 — Filmes e quem os avaliou
SELECT F.TITULO, A.NOTA, U.NOME
FROM USUARIOS U 
INNER JOIN AVALIACOES A ON A.USUARIO_ID = U.USUARIO_ID
INNER JOIN FILMES F ON F.FILME_ID = A.FILME_ID
ORDER BY F.TITULO;

-- Consulta 03 — Filmes avaliados com nota 5 
SELECT F.TITULO, U.NOME
FROM USUARIOS U 
INNER JOIN AVALIACOES A ON A.USUARIO_ID = U.USUARIO_ID
INNER JOIN FILMES F ON F.FILME_ID = A.FILME_ID
WHERE A.NOTA = 5
ORDER BY F.TITULO;

-- Consulta 04 — Usuários mais ativos
SELECT U.NOME, COUNT(*) AS TOTAL_AVALIACOES
FROM USUARIOS U 
INNER JOIN AVALIACOES A ON A.USUARIO_ID = U.USUARIO_ID
GROUP BY U.NOME
ORDER BY TOTAL_AVALIACOES DESC;

-- Consulta 05 — Média de notas por filme
SELECT F.TITULO, ROUND(AVG(A.NOTA),2) AS MEDIA_NOTAS
FROM FILMES F
INNER JOIN AVALIACOES A ON A.FILME_ID = F.FILME_ID
GROUP BY F.TITULO
ORDER BY MEDIA_NOTAS DESC;

-- Consulta 06 — Todos os filmes — com ou sem avaliação
SELECT F.TITULO, F.GENERO, COUNT(*) AS TOTAL_AVALIACOES
FROM FILMES F
LEFT JOIN AVALIACOES A ON A.FILME_ID = F.FILME_ID
GROUP BY F.TITULO, F.GENERO
ORDER BY TOTAL_AVALIACOES DESC;


